<<<<<<< HEAD
language: java
jdk:
  - oraclejdk8
sudo: false

env:
  - NODE_VERSION=0.12

install:
  - nvm install $NODE_VERSION
  - npm install

=======
language: node_js
node_js:
  - '8'
sudo: false

>>>>>>> 7da188a44e11372058b1e374a344f4478e4db3d2
branches:
  only:
    - master

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: nqa-social-media
<<<<<<< HEAD
=======

after_deploy:
  - echo "Deploy Complete"
>>>>>>> 7da188a44e11372058b1e374a344f4478e4db3d2
